#!/usr/bin/env python

import main
import clock

mainapplet = clock.ClockApplet()
def delete_main(window, dev):
	window.hide()
	return True
main.main_window.connect('delete-event', delete_main)

main.main()
