#!/usr/bin/env python

import findrox; findrox.version(1, 9, 8)
import rox

import os
__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

rox.setup_app_options('Memo')

from rox.Menu import set_save_name
set_save_name('Memo')

import Window, memos

# All options must be registered by the time we get here
rox.app_options.notify()

memo_list = memos.MasterList()
Window.Window(memo_list)

rox.mainloop()
